# لا حول ولا قوّة الا با لله
name: Excecute ssh command in remote server
on:
  push:
    branches:
      - master
      

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: sudo sh /home/ubuntu/quran-gql/starter.sh 

